# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqi',
            name='aqi_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aqi',
            name='aqi_pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
